sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker build -t keboola/processor-flatten-folders .
script: docker run keboola/processor-flatten-folders composer ci
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notifications:
  slack:
    secure: IfCHkfh9V/ofnuinixr9gLK4w+PdEh/jSSMxdAFNMbOmcNjlwImHZgOFFtI0WSngj0Q6b5wuMKbKGwrXdu34LJZGH51hTSfsCGHKTecyaL+PGLp+w0kDPTwALorsfodievrBwAA4DSOVZbSkJTo2MK410MhUM7HMGR8IJRFLAaNZH8GPYbrJ2MmOkdG64QepqIyfL17/+nNj93ylxKjRCIWspYg1j6BKHnlV5rJ8DZ1CI0miZBp7BVR7qSl32b9wD6HlEHV2hac8xdCr1/eeNOw81KdDU9ETkio6ujN7nA9zmjihglyLdSiZGkDF8T03Inbr/h+zzxYTVxQ3HXzsJoOc2+MNkeZPaHuyzpZAR3kBvD3Ud0lYuico0eDTRrny4Go62UOFmqDf2eyDea+f72Fp03ATBoWrsBlBJqvcDPqjLrdjB4hRNyldxQfPNyyFXDp2/Uw/Pyln0/sMMuoVwf27i97GDZ4iqMxvZOMDeT0WPTz1J+qsfO00ISD2OuBnr46qR268p6UKCsufJxEmlJ2ZhbFyGjfllp2Bn6qxqtGYf/VK0kw2xHXv9jZZVjV3vXG9Xb5Jr1Q71+W0dkwOLul8Juyvvb1nSnq7kFIW2MU/qQQILw8FcsEFEk30PvDX7Egi6WnsPIu90LA/d/ZYLfrJRpIsTNAFBCFstXqt6RU=
