sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker build -t keboola/processor-flatten-folder .
  - docker run keboola/processor-flatten-folder composer ci
script: docker-compose run dev php /code/tests/run.php
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
