sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker build -t keboola/processor-flatten-folder .
script: docker run keboola/processor-flatten-folder composer ci
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
